### ISSUE TITLE
余弦分类器

### ISSUE THREAD

**Issue by ffxxjj** [Z-ZHHH/CVPR23-DML#1]
尊敬的作者您好：
        非常感谢您针对OOD检测进行了更深层次的探讨，并为此做出了贡献，但我注意到您在论文中提到了有关余弦分类器的做法，但在您提供的代码中我并没有找到相关的实现部分，希望您能给我一些提示。

**Comment by Z-ZHHH** [comment]
您好，余弦分类器相比于线性分类器，对最后一层特征和分类器fc分别进行了归一化，同时对于fc(x)还需要乘上一个缩放因子。
  具体在代码里：[Norm on features](https://github.com/Z-ZHHH/CVPR23-DML/blob/68c117f0e2960d1ebe5e6e3e40cafe3e25f46fb2/models/resnet34.py#L120C1-L124C29),  [Norm on classifier](https://github.com/Z-ZHHH/CVPR23-DML/blob/68c117f0e2960d1ebe5e6e3e40cafe3e25f46fb2/models/resnet34.py#L77C1-L82C63)。
  在网络model初始化时会指定两个参数`use_norm=True, feature_norm=True`就是使用余弦分类器，`use_norm=False, feature_norm=False`就是使用线性分类器。
希望有帮助。

**Comment by Z-ZHHH** [comment]
余弦分类器的使用：[Matching Networks for One Shot Learning
](https://proceedings.neurips.cc/paper/2016/file/90e1357833654983612fb05e3ec9148c-Paper.pdf)和[Quora Q&A](https://www.quora.com/Why-does-cosine-similarity-work-in-Machine-Learning)，本质是衡量两个向量的余弦相似性、余弦距离度量，类似的距离度量还包括`scipy.spatial.distance.cdist`方法使用的`'euclidean'、'cityblock'`等。<br>
Vision-Language model也使用这种分类方式，如[CLIP模型](https://github.com/openai/CLIP)的zero-shot分类：<br>
```
# Pick the top 5 most similar labels for the image
image_features /= image_features.norm(dim=-1, keepdim=True)
text_features /= text_features.norm(dim=-1, keepdim=True)
similarity = (100.0 * image_features @ text_features.T).softmax(dim=-1)
values, indices = similarity[0].topk(5)
```

**Comment by ffxxjj** [comment]
非常感谢您的回答，我去仔细研究一下
